# aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias back='cd $OLDPWD'
# alias c='clear'
alias cd..='cd ..'
alias cp='cp -iv'
alias chmod="chmod -c"
alias df='df -h -x squashfs -x tmpfs -x devtmpfs'
alias diff='colordiff'
# already in default bashrc
# alias grep='grep --color=auto'
# alias fgrep='fgrep --color=auto'
# alias egrep='egrep --color=auto'

# alias e="vim -O "
# alias E="vim -o "
alias extip='curl icanhazip.com'
# alias ll='ls -lhFa --time-style=long-iso --color=auto'
alias lsmount='mount |column -t'
alias mkdir='mkdir -pv'
alias ports='netstat -tulanp'
alias h='history'
alias j='jobs -l'
alias mv='mv -iv'
alias ssha='eval $(ssh-agent) && ssh-add'
alias tn=' tmux new -s'
alias watch='watch -d'
alias weather='curl wttr.in'
alias wget='wget -c'

## get top process eating memory
alias mem5='ps auxf | sort -nr -k 4 | head -5'
alias mem10='ps auxf | sort -nr -k 4 | head -10'

## get top process eating cpu ##
alias cpu5='ps auxf | sort -nr -k 3 | head -5'
alias cpu10='ps auxf | sort -nr -k 3 | head -10'

## List largest directories (aka "ducks")
alias dir5='du -cksh * | sort -hr | head -n 5'
alias dir10='du -cksh * | sort -hr | head -n 10'

# Safetynets
# do not delete / or prompt if deleting more than 3 files at a time #
alias rm='rm -I --preserve-root'

# confirmation #
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'

# Parenting changing perms on / #
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'

# reload bash config
alias reload="source ~/.bashrc"

# Manage packages easier
if [ -f /usr/bin/apt ]; then
  # alias update='sudo apt update'
  alias upd='sudo apt update && sudo apt dist-upgrade -y && sudo apt autoremove && sudo apt clean'
  alias install='sudo apt install'
fi
