---
- name: packages |install | install apt packages
  tags: packages,system,settings
  block:
    - name: install | apt packages
      package:
        state: latest
        name:
          # basic stuff and dependencies
          - jq
          - mc
          - bat
          - duf
          - git
          - tig
          - curl
          - file
          - htop
          - lsof
          - ncdu
          - tre-command
          - tmux
          - wget
          - gnupg
          # - iotop
          - rsync
          - sshfs
          - whois
          - xclip
          # - browsh
          - procps
          - screen
          - glances
          - hddtemp
          - python3
          - dnsutils
          - neofetch
          - colordiff
          # - diff-so-fancy
          - dconf-cli
          - lm-sensors
          - nfs-common
          - traceroute
          # - boot-repair
          - python3-pip
          - python3-psutil
          - build-essential
          - ca-certificates
          - grub-customizer
      register: packages
      until: packages is success
      retries: 3
      delay: 10
  rescue:
    - set_fact: task_failed=true
